
on: 
  push:
    branch:
      - master
name: proselint-this-filthy-repo 
jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run proselint
      uses: amperser/proselint@master
